config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
 root to: 'lists#index'
  resources :lists, except: :index do
    resources :bookmarks, only: [:create, :delete]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, length: { minimum: 6 }
  validates :movie, uniqueness: { scope: :list }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks
  has_many :movies, through: :bookmarks, dependent: :destroy
  validates :name, uniqueness: true, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, uniqueness: true, presence: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @list = List.find(params[:list_id])
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      # raise
      render html: helpers.tag.strong('Comment needs at least 6 character, and no same movie can be added')
    end
  end

  def destroy

  end

  private
  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id, :list_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def new
    @list = List.new
  end

  def show
    @list = List.find(params[:id])
    @bookmark = Bookmark.new
  end

  def edit
    @list = List.find(params[:id])
  end

  def index
    @lists = List.all
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def update
    @list = List.find(params[:id])
    @list.update(list_params)
    redirect_to root_path
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/_form.html.erb
<%= simple_form_for [ @list, @list.bookmarks.build] do |f| %>
  <%= f.association :movie %>
  <%= f.input :comment %>
  <%= f.submit "Add a movie", class: "btn btn-primary" %>
<% end %>

app/views/bookmarks/error.html.erb
<h1>Can't create a duplicate list</h1>

app/views/bookmarks/new.html.erb
<!-- app/views/reviews/new.html.erb -->
<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <nav style="padding: 4px 10px" class="navbar navbar-light bg-light justify-content-between">
      <%= image_tag "projector.png", alt: "movie", width: 20 %>
      <p style="margin: 0px; padding: 4px 10px">
        <%= link_to new_list_path, class:"link" do %>
          <i class="far fa-plus-square"></i>
        <% end %>
      </p>
    </nav>
    <div class="home-banner">
      <h1>Save any kind of movies</h1>
    </div>
    <%= yield %>
  </body>
</html>

app/views/lists/_list.html.erb
<div class="card bg-dark text-white m-1">
  <%= image_tag("banner_picture.jpg", size: "300x200", alt: "Edit Entry") %>
  <div class="card-img-overlay text-center" style="width: 140px; margin: 0 auto;">
    <h5><%= link_to list.name, list_path(list), class: "text-info" %></h5>
    <%= link_to edit_list_path(list), class: "text-info" do %>
      <i class="far fa-edit"></i>
    <% end %>
  </div>
</div>

app/views/lists/edit.html.erb
<%= simple_form_for(@list) do |f| %>
  <%= f.input :name %>
  <%= f.submit %>
<% end %>

app/views/lists/index.html.erb
  <div class="card-group">
    <%= render @lists %>
  </div>

app/views/lists/new.html.erb
<h1>Lists#new</h1>
<p>Find me in app/views/lists/new.html.erb</p>

<%= simple_form_for(@list) do |f| %>
  <%= f.input :name %>
  <%= f.submit %>
<% end %>

app/views/lists/show.html.erb
<div class="container d-flex p-2 flex-column justify-content-between">
  <h1 class="p-2"><%= @list.name %></h1>
  <div class="card-deck p-2">
    <% @list.bookmarks.each do |bookmark| %>
      <div class="card col-6 col-sm-6">
        <%= image_tag "#{bookmark.movie.poster_url}", alt: "movie", width: "200", class: "card-img-top"  %>
        <div class="card-body">
          <h5 class="card-title"><%= bookmark.movie.title %></h5>
        </div>
      </div>
    <% end  %>
  </div>
  <div>
  <%= render 'bookmarks/form' %>
  </div>
  <div class="p-2">
    <p><%= link_to "Back", root_path %></p>
  </div>
</div>